kind: ReplicaSet
apiVersion: apps/v1
metadata: 
  name: nginx-rs
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-rs-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-rs-container
        image: nginx:stable-alpine3.21-perl
        ports:
        - containerPort: 80
